FROM ubuntu:latest

RUN apt-get update                  \
&& apt-get -y install python3       \
&& apt-get -y install python3-pip   \
&& apt-get -y install virtualenv    \
&& apt-get -y install git           \
&& apt-get -y install vim


