version: '3'
services:
    ping:
        image: ping:0.0.1
        deploy:
            replicas: 6
        networks:
            - ping-net
        stdin_open: true
        tty: true
networks:
    ping-net:
        driver: overlay

##
# docker stack deploy --compose-file docker-compose.yml ping-stack

